#!/bin/bash
# INSTALLATION
# Sur votre jeedom
# - sudo apt install android-tools-adb
# Sur votre mini4k
# - paramètres
# - À propos
# - Appuyer sur OK 8 fois sur la ligne Build (passage en mode développeur)
# - paramètres
# - Options pour les développeurs (Dernière options de la 2ème ligne)
# - Débogage
# - Débogage USB
# - Activé
# UTILISATION
# À la première utilisation, une demande d'authorisation va s'afficher sur votre télé. Cocher toujours accepter
# - Créer un script : 
# -- "Type script" : Script
# -- "Type" : - Action
#             - Message
# -- "Requête" : /var/www/html/plugins/script/core/ressources/mini4k_cmd IP_DE_VOTRE_MINI4K" #message#
# Commandes acceptées :
# - Logical ID

mini4k_ip=$1
param=$2
is_valid_cmd=0
if [[ $param =~ ^[0-9]+$ ]]
then
    chaine=($(echo $param |sed  's/\(.\)/\1 /g'))

    cmd="input "
    for element in "${chaine[@]}"
    do
        cmd="$cmd keyevent $(($element + 7)) "
    done
    is_valid_cmd=1
fi
if [[ $param == "power" || $param == "OFF" ]]
then
    sudo /usr/bin/adb connect $mini4k_ip
    statut=$(sudo /usr/bin/adb shell dumpsys power -h | grep "Display Power" | sed 's/\.*Display Power: state=\(\w\)/\1/' | tr -d '\r\n')
    sudo /usr/bin/adb disconnect
    if [[ $param != $statut || $param == "power" ]]
    then
        cmd="input keyevent 26"
        is_valid_cmd=1
    fi
fi
if [[ $param == "mute" ]]
then
    cmd="input keyevent 164"
    is_valid_cmd=1
fi
  
if [[ $param == "down" ]]
then
    cmd="input keyevent 20"
    is_valid_cmd=1
fi

if [[ $param == "up" ]]
then
    cmd="input keyevent 19"
    is_valid_cmd=1
fi

if [[ $param == "left" ]]
then
    cmd="input keyevent 21"
    is_valid_cmd=1
fi

if [[ $param == "right" ]]
then
    cmd="input keyevent 22"
    is_valid_cmd=1
fi
if [[ $param == "red" ]]
then
    cmd="input keyevent 183"
    is_valid_cmd=1
fi
if [[ $param == "green" ]]
then
    cmd="input keyevent 184"
    is_valid_cmd=1
fi
if [[ $param == "yellow" ]]
then
    cmd="input keyevent 185"
    is_valid_cmd=1
fi
if [[ $param == "blue" ]]
then
    cmd="input keyevent 186"
    is_valid_cmd=1
fi
if [[ $param == "home" ]]
then
    cmd="input keyevent 170"
    is_valid_cmd=1
fi
if [[ $param == "rec" ]]
then
    cmd="input keyevent 130"
    is_valid_cmd=1
fi
if [[ $param == "bwd" ]]
then
    cmd="input keyevent 275"
    is_valid_cmd=1
fi
if [[ $param == "prev" ]]
then
    cmd="input keyevent 89"
    is_valid_cmd=1
fi
if [[ $param == "play" ]]
then
    cmd="input keyevent 85"
    is_valid_cmd=1
fi
if [[ $param == "fwd" ]]
then
    cmd="input keyevent 90"
    is_valid_cmd=1
fi
if [[ $param == "next" ]]
then
    cmd="input keyevent 90"
    is_valid_cmd=1
fi  
if [[ $param == "ok" ]]
then
    cmd="input keyevent 23"
    is_valid_cmd=1
fi  

if [[ $param == "vol_inc" ]]
then
    cmd="input keyevent 24"
    is_valid_cmd=1
fi  
if [[ $param == "vol_dec" ]]
then
    cmd="input keyevent 25"
    is_valid_cmd=1
fi 

if [[ $param == "prgm_inc" ]]
then
    cmd="input keyevent 166"
    is_valid_cmd=1
fi
if [[ $param == "prgm_dec" ]]
then
    cmd="input keyevent 167"
    is_valid_cmd=1
fi

if [[ $is_valid_cmd -eq 1 ]]
then
    ok=1
    retry=0
    while [[ $ok -gt 0 && $retry -lt 2 ]]
    do
    	sudo /usr/bin/adb connect $mini4k_ip
    	sudo /usr/bin/adb shell $cmd
     	ok=$?
    	sudo /usr/bin/adb disconnect
      	retry=$(( $retry + 1))
	
    done
fi
